events {}

http {


    # Ambiente activo actualmente
    upstream springboot_backend {


        # BLUE activo
        server 192.168.1.171:8081;


    }


    # Ambiente nuevo para pruebas
    upstream springboot_green {


        # GREEN
        server 192.168.1.171:8082;


    }



    server {


        listen 80;


        server_name localhost;



        location / {


            proxy_pass http://springboot_backend;


            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;


        }



        location /health {


            proxy_pass http://springboot_backend/health;


        }



        location /api/instance {


            proxy_pass http://springboot_backend/api/instance;


        }



    }

}